<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, onBeforeRouteLeave } from 'vue-router'
import { useProject } from '@/composables/useProject'
import { repository } from '@/data/database'
import { History } from '@/domain/history'
import { SOURCE_LABELS, type Project, type Vec3 } from '@/domain/types'
import { distance, geometryBounds } from '@/domain/geometry'
import { errorMessage } from '@/domain/validation'
import { lengthLabel } from '@/composables/useSettings'
import { toast } from '@/composables/useToasts'
import AppIcon from '@/components/AppIcon.vue'
import SceneViewer from '@/components/SceneViewer.vue'
import NoticeBox from '@/components/NoticeBox.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
const route = useRoute(), id = computed(() => String(route.params.id)), { project, scenes, loading, error, reload } = useProject(id)
const draft = ref<Project>(), selected = ref(''), tab = ref('details'), dirty = ref(false), busy = ref(false), history = new History<Project>(), historyTick = ref(0), pending = ref<Vec3[]>([]), label = ref(''), note = ref(''), removeId = ref('')
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value))
watch(project, p => { if (p) { draft.value = clone(p); selected.value = p.scenes[0]?.id || ''; dirty.value = false; history.clear(); historyTick.value++ } })
const current = computed(() => draft.value?.scenes.find(s => s.id === selected.value))
const rendered = computed(() => draft.value ? scenes.value.flatMap(s => { const scene = draft.value!.scenes.find(d => d.id === s.scene.id); return scene ? [{ geometry: s.geometry, scene: clone(scene) }] : [] }) : [])
const canUndo = computed(() => { void historyTick.value; return history.canUndo }), canRedo = computed(() => { void historyTick.value; return history.canRedo })
function checkpoint(): void { if (!draft.value) return; history.record(clone(draft.value)); historyTick.value++; dirty.value = true }
function undo(): void { if (!draft.value) return; const value = history.undo(clone(draft.value)); if (value) draft.value = value; dirty.value = true; pending.value = []; historyTick.value++ }
function redo(): void { if (!draft.value) return; const value = history.redo(clone(draft.value)); if (value) draft.value = value; dirty.value = true; pending.value = []; historyTick.value++ }
async function save(): Promise<void> { if (!draft.value || !project.value || busy.value) return; busy.value = true; try { const result = await repository.save(clone(draft.value), project.value.revision); project.value = result; dirty.value = false; toast('Your edits are saved on this device.', 'success') } catch (e) { toast(errorMessage(e), 'error') } finally { busy.value = false } }
function hit(point: { sceneId: string; position: Vec3 }): void { if (point.sceneId !== selected.value) return; if (tab.value === 'hotspots') pending.value = [point.position]; else if (tab.value === 'measurements') pending.value = pending.value.length >= 2 ? [point.position] : [...pending.value, point.position] }
function addPoint(): void { if (!draft.value || !selected.value || !label.value.trim() || !pending.value.length) return; checkpoint(); if (tab.value === 'hotspots') draft.value.annotations.push({ id: crypto.randomUUID(), sceneId: selected.value, position: pending.value[0], label: label.value.trim(), note: note.value.trim() }); else if (pending.value.length === 2) draft.value.measurements.push({ id: crypto.randomUUID(), sceneId: selected.value, a: pending.value[0], b: pending.value[1], label: label.value.trim() }); pending.value = []; label.value = ''; note.value = '' }
function crop(): void { if (!current.value) return; const original = scenes.value.find(s => s.scene.id === selected.value); if (original) { checkpoint(); current.value.crop = geometryBounds(original.geometry) } }
function removeScene(): void { if (!draft.value) return; checkpoint(); const sceneId = removeId.value; draft.value.scenes = draft.value.scenes.filter(s => s.id !== sceneId); draft.value.annotations = draft.value.annotations.filter(s => s.sceneId !== sceneId); draft.value.measurements = draft.value.measurements.filter(s => s.sceneId !== sceneId); draft.value.rooms = draft.value.rooms.filter(s => s.sceneId !== sceneId); selected.value = draft.value.scenes[0]?.id || ''; removeId.value = '' }
watch([selected, tab], () => { pending.value = [] })
onBeforeRouteLeave(() => !dirty.value || window.confirm('Leave without saving these edits? The saved project will not change.'))
</script>
<template><div class="editor-page"><header class="viewer-header"><RouterLink :to="`/projects/${id}`" class="icon-button" aria-label="Back to space"><AppIcon name="back"/></RouterLink><div><strong>{{ draft?.name || 'Edit space' }}</strong><small>{{ dirty ? 'Unsaved changes' : 'All changes saved locally' }}</small></div><div class="viewer-header-actions"><button class="icon-button" :disabled="!canUndo" aria-label="Undo" @click="undo"><AppIcon name="undo"/></button><button class="icon-button" :disabled="!canRedo" aria-label="Redo" @click="redo"><AppIcon name="redo"/></button><button class="btn btn-primary btn-sm" :disabled="busy || !dirty || !!error" @click="save">{{ busy ? 'Saving…' : 'Save changes' }}</button></div></header><div v-if="loading" class="loading-state">Preparing your workspace…</div><NoticeBox v-if="error" kind="error">{{ error }}<button @click="reload">Reload</button></NoticeBox><div v-if="draft" class="editor-layout"><div class="editor-canvas"><SceneViewer :scenes="rendered" :annotations="draft.annotations" :measurements="draft.measurements" :pick="tab === 'hotspots' || tab === 'measurements'" :selected-scene-id="selected" :pending-points="pending" @pick="hit"/><div v-if="['hotspots', 'measurements'].includes(tab)" class="canvas-instruction"><AppIcon :name="tab === 'hotspots' ? 'pin' : 'ruler'" :size="18"/>{{ tab === 'hotspots' ? 'Tap a surface to place a hotspot.' : `Tap two surfaces on the selected section. ${pending.length}/2 selected.` }}</div></div><aside class="editor-panel"><div class="editor-tabs" role="tablist" aria-label="Editing tools"><button v-for="t in [{ id:'details', icon:'edit', text:'Details' },{ id:'sections', icon:'layers', text:'Sections' },{ id:'hotspots', icon:'pin', text:'Hotspots' },{ id:'measurements', icon:'ruler', text:'Measure' },{ id:'photos', icon:'camera', text:'Photos' }]" :key="t.id" role="tab" :aria-selected="tab === t.id" :class="{ active:tab === t.id }" @click="tab = t.id"><AppIcon :name="t.icon" :size="19"/><span>{{ t.text }}</span></button></div>
<div v-if="tab === 'details'" class="editor-form"><h2>The story of your space</h2><label class="form-label" for="edit-name">Space name</label><input id="edit-name" v-model="draft.name" class="form-control" maxlength="100" required @focus="checkpoint"><label class="form-label" for="edit-location">Location</label><input id="edit-location" v-model="draft.location" class="form-control" maxlength="200" @focus="checkpoint"><label class="form-label" for="edit-notes">Notes</label><textarea id="edit-notes" v-model="draft.notes" class="form-control" rows="7" maxlength="5000" placeholder="What makes this space yours?" @focus="checkpoint"/><NoticeBox>Your notes are private to this local project. Exported W3D backups include them.</NoticeBox><RouterLink :to="`/projects/${id}/floorplan`" class="btn btn-outline-primary w-100"><AppIcon name="map"/>Open floor plan tools</RouterLink></div>
<div v-else-if="tab === 'photos'" class="editor-form"><h2>Photo captions</h2><p>Add context to your reference images.</p><div v-for="photo in draft.photos" :key="photo.id" class="record-editor"><strong>{{ photo.name }}</strong><label class="form-label" :for="`caption-${photo.id}`">Caption</label><input :id="`caption-${photo.id}`" v-model="photo.caption" class="form-control" maxlength="500" @focus="checkpoint"><button class="text-link danger-text mt-2" @click="checkpoint(); draft.photos = draft.photos.filter(p => p.id !== photo.id)"><AppIcon name="trash" :size="16"/>Remove photo from project</button></div><p v-if="!draft.photos.length">Add reference photos from the space overview.</p><p class="fine-print">Removed photos stay recoverable with Undo until you save the project.</p></div>
<div v-else class="editor-form"><label class="form-label" for="selected-section">Selected scan section</label><select id="selected-section" v-model="selected" class="form-select"><option v-for="s in draft.scenes" :key="s.id" :value="s.id">{{ s.name }}</option></select><p v-if="!current">Add a scan or import a model to start editing geometry.</p><template v-if="current && tab === 'sections'"><label class="form-label" for="section-name">Section name</label><input id="section-name" v-model="current.name" class="form-control" maxlength="100" @focus="checkpoint"><p class="fine-print mt-2">{{ SOURCE_LABELS[current.source] }}</p><label class="form-label" for="section-status">Review status</label><select id="section-status" v-model="current.status" class="form-select" @focus="checkpoint"><option value="review">Needs review</option><option value="saved">Reviewed & saved</option></select><h3 class="mt-4">Align this section</h3><p class="fine-print">Independent captures have separate origins. Align manually against known points; this is not automatic stitching.</p><fieldset><legend>Position · metres</legend><div class="xyz-inputs"><label v-for="(axis, k) in ['X','Y','Z']" :key="axis">{{ axis }}<input v-model.number="current.transform.position[k]" type="number" class="form-control" step="0.05" min="-10000" max="10000" @focus="checkpoint"></label></div></fieldset><fieldset><legend>Rotation · degrees</legend><div class="xyz-inputs"><label v-for="(axis, k) in ['X','Y','Z']" :key="axis">{{ axis }}<input v-model.number="current.transform.rotation[k]" type="number" class="form-control" step="1" min="-360" max="360" @focus="checkpoint"></label></div></fieldset><label class="form-label" for="section-scale">Scale · verify with a known length</label><input id="section-scale" v-model.number="current.transform.scale" class="form-control" type="number" min="0.0001" max="1000" step="0.01" @focus="checkpoint"><h3 class="mt-4">Non-destructive crop</h3><p class="fine-print">Crop bounds use section-local metres. Original geometry remains in the backup.</p><button v-if="!current.crop" class="btn btn-outline-primary w-100" @click="crop"><AppIcon name="crop"/>Set crop bounds</button><template v-else><fieldset v-for="side in ['min','max'] as const" :key="side"><legend>{{ side === 'min' ? 'Minimum' : 'Maximum' }}</legend><div class="xyz-inputs"><label v-for="(axis, k) in ['X','Y','Z']" :key="axis">{{ axis }}<input v-model.number="current.crop[side][k]" type="number" class="form-control" step="0.05" @focus="checkpoint"></label></div></fieldset><button class="text-link" @click="checkpoint(); delete current.crop">Reset crop</button></template><NoticeBox v-for="(warning, i) in current.warnings" :key="i" kind="warning">{{ warning }}</NoticeBox><button class="text-link danger-text mt-4" @click="removeId = current.id"><AppIcon name="trash" :size="17"/>Remove this section</button></template>
<template v-else-if="current"><h2 class="mt-4">{{ tab === 'hotspots' ? 'A point worth exploring.' : 'Get a sense of scale.' }}</h2><p>{{ tab === 'hotspots' ? 'Place a marker on a surface, then give it a title. Hotspots become stops in the viewer.' : 'Select two points on the same section. Values remain approximate, especially on imported or incomplete models.' }}</p><label class="form-label" for="point-label">{{ tab === 'hotspots' ? 'Hotspot title' : 'Measurement label' }}</label><input id="point-label" v-model="label" class="form-control" maxlength="100" :placeholder="tab === 'hotspots' ? 'e.g. Reading nook' : 'e.g. Sofa width'"><template v-if="tab === 'hotspots'"><label class="form-label" for="point-note">Description</label><textarea id="point-note" v-model="note" class="form-control" rows="3" maxlength="1000"/></template><div v-if="pending.length === 2" class="measurement-result">≈ {{ lengthLabel(distance(pending[0], pending[1]) * current.transform.scale) }}</div><button class="btn btn-primary w-100 mt-3" :disabled="!label.trim() || pending.length !== (tab === 'hotspots' ? 1 : 2)" @click="addPoint"><AppIcon name="plus"/>Save {{ tab === 'hotspots' ? 'hotspot' : 'measurement' }}</button><p class="fine-print mt-3">Keyboard alternative: enter local coordinates below rather than clicking the canvas.</p><button class="text-link" @click="pending = tab === 'hotspots' ? [[0,0,0]] : [[0,0,0],[1,0,0]]">Enter coordinates</button><div v-for="(p, index) in pending" :key="index" class="xyz-inputs mt-2"><label v-for="(axis, k) in ['X','Y','Z']" :key="axis">{{ axis }}{{ index + 1 }}<input v-model.number="p[k]" type="number" class="form-control" step="0.01"></label></div><h3 class="mt-4">Saved {{ tab === 'hotspots' ? 'hotspots' : 'measurements' }}</h3><template v-if="tab === 'hotspots'"><div v-for="a in draft.annotations.filter(a => a.sceneId === selected)" :key="a.id" class="saved-point"><span>{{ a.label }}</span><button class="icon-button" :aria-label="`Remove ${a.label}`" @click="checkpoint(); draft.annotations = draft.annotations.filter(p => p.id !== a.id)"><AppIcon name="trash" :size="17"/></button></div></template><template v-else><div v-for="m in draft.measurements.filter(m => m.sceneId === selected)" :key="m.id" class="saved-point"><span>{{ m.label }}<small>≈ {{ lengthLabel(distance(m.a,m.b) * current.transform.scale) }}</small></span><button class="icon-button" :aria-label="`Remove ${m.label}`" @click="checkpoint(); draft.measurements = draft.measurements.filter(p => p.id !== m.id)"><AppIcon name="trash" :size="17"/></button></div></template></template></div></aside></div><ConfirmDialog v-if="removeId" title="Remove this scan section?" message="Its hotspots, measurements and room outlines will be removed too. You can undo this until you save." confirm-label="Remove section" danger @cancel="removeId = ''" @confirm="removeScene"/></div></template>
