<script setup lang="ts">
import { computed, ref } from 'vue'
import AppIcon from '@/components/AppIcon.vue'
import PageHeading from '@/components/PageHeading.vue'
const search = ref('')
const questions = [
 { q:'How do I get a useful room scan?', a:'Use a well-lit, static space. Walk slowly sideways instead of only rotating in place. Revisit surfaces from several angles while keeping features in view. Start with small sections, and inspect the saved result for holes. Keep a clear walking path and never watch the screen while approaching stairs.' },
 { q:'Does an ordinary phone camera guarantee 3D scanning?', a:'No. Camera video is not a reconstruction engine. This app uses ARKit mesh reconstruction in the supported iOS native build, ARCore Depth in the supported Android native build, or actual WebXR CPU depth in a supported browser. When those capabilities are unavailable, the app offers reference photos or model import without pretending a scan happened.' },
 { q:'Can I scan without an Internet connection?', a:'The implemented capture loops and geometry processing are local. Install the app and necessary platform components first. The browser version also needs its application files cached before going offline. ARCore may need an initial installation or update. There is no cloud reconstruction service, no cloud anchors and no required account in this application.' },
 { q:'Will separate rooms line up automatically?', a:'Not across separate capture sessions. Each session starts in a new local coordinate frame. Scan connected areas continuously when practical, within the memory budget, or use the editor to translate, rotate and scale separate sections against known features. Do not treat visually plausible alignment as a surveyed whole-house model.' },
 { q:'Why are mirrors, windows and parts of the room missing?', a:'Reflective, transparent, low-texture, very dark, distant or unseen surfaces can produce unreliable or absent depth. The app does not invent unseen rooms or fill holes with guessed geometry. Add reference photos and inspect incomplete areas before using the model.' },
 { q:'What is the difference between a mesh and a photographic tour?', a:'A mesh describes observed surfaces. Native capture stores geometry, with sampled vertex colour where available; browser depth uses a uniform display colour. This is not Gaussian splatting, texture-atlas generation or photogrammetric reconstruction. The interactive viewer can navigate saved geometry and named hotspots; it is not a promise of photographic fidelity.' },
 { q:'How do I create a floor plan?', a:'Open a project’s Floor plan view and trace floor corners in top-down view, or enter known local X,Z coordinates. Name the room, choose a floor number and save the outline. The SVG export uses those actual saved outlines. This version does not automatically detect walls, doors or room semantics.' },
 { q:'Are dimensions accurate enough for construction?', a:'No survey certification is implied. Model scale, tracking drift, depth noise and manual point placement affect distances. Imported models initially assume metres, so verify scale against a known dimension. Use qualified measurement equipment and professional review for construction, legal or safety decisions.' },
 { q:'What happens when scanning is interrupted?', a:'The native adapters keep periodic local recovery snapshots while a capture is active. Browser scans save periodic geometry checkpoints to IndexedDB. Open the project’s capture screen to review an unfinished capture. Recovery preserves the old geometry; it does not pretend a restarted tracking session can continue in the same coordinate frame. Data since the last successful checkpoint may be lost.' },
 { q:'What should I do if storage is full?', a:'Stop capture and export important work. Keep backups outside this app before deleting projects. Browser quota is advisory and storage can be evicted; request persistence in Settings, but do not rely on it as a backup. Failed saves must remain visibly failed and recovery copies are retained where possible.' },
 { q:'Which model formats can I import and export?', a:'Import geometry-only, self-contained GLB 2.0, PLY or OBJ. Textures, external resources, animations and compressed GLB extensions are rejected or not imported, as explained before import. Export GLB, binary PLY or OBJ for other tools. W3D backs up the full project and can be passphrase encrypted. W3D restoration always creates a separate copy.' },
 { q:'Is my home automatically published or shared with WiseStay?', a:'No. The workspace is local-only. There is no remote publication button, public share-link generator or backend login pretending to be integrated. Export and share are deliberate file operations. Future WiseStay listing integration must enforce its own identity, authority and public/private media rules.' },
 { q:'What does “Saved” mean?', a:'It means the project or scan was committed to this device’s local storage. It does not mean uploaded, backed up, accurately measured, independently reviewed or physically qualified. Sample geometry is always labelled illustrative and never used as a camera fallback.' },
 { q:'How do I report a problem without sharing my house?', a:'Record the app version, platform, device capability result, operation attempted and exact error text. Avoid attaching a scan, photo, backup or private location unless you deliberately choose to disclose it. Review source and development instructions in this project’s repository.' },
]
const results = computed(() => questions.filter(x => `${x.q} ${x.a}`.toLowerCase().includes(search.value.toLowerCase())))
</script>
<template><div class="container support-wrapper guide-container"><PageHeading eyebrow="A BETTER SCAN STARTS HERE" title="A little guidance. A clearer perspective." subtitle="Practical answers for scanning, editing and keeping your spaces safe."/><section class="guide-steps"><div v-for="(step,i) in [{ icon:'sun', title:'Let the light in.', text:'Bright, even light helps the phone track real surfaces.' },{ icon:'scan', title:'Go slowly. Look around.', text:'Move sideways and revisit surfaces from new angles.' },{ icon:'eye', title:'Review what you captured.', text:'Check holes and scale. Add photos where geometry is missing.' }]" :key="step.title" class="card"><span class="step-number">0{{ i + 1 }}</span><AppIcon :name="step.icon" :size="33"/><h2>{{ step.title }}</h2><p>{{ step.text }}</p></div></section><div class="faq-search-form search-field"><AppIcon name="search"/><input v-model="search" class="form-control" type="search" placeholder="What would you like to know?" aria-label="Search help topics"></div><section class="accordian-area-wrapper"><h2 class="accordian-title">Answers, without the guesswork.</h2><details v-for="item in results" :key="item.q" class="card accordian-card"><summary>{{ item.q }}<AppIcon name="plus" :size="19"/></summary><p>{{ item.a }}</p></details><p v-if="!results.length" class="empty-state">No matching help topics. Try “offline”, “camera”, “export” or “floor plan”.</p></section><div class="help-footer"><AppIcon name="phone" :size="27"/><div><h3>Not sure what this device supports?</h3><p>Check real capabilities before opening the camera.</p></div><RouterLink to="/device" class="btn btn-outline-primary">Check device<AppIcon name="arrow" :size="17"/></RouterLink></div></div></template>
