<script setup lang="ts">
import { computed, ref } from 'vue'
import { useLibrary } from '@/composables/useLibrary'
import AppIcon from '@/components/AppIcon.vue'
import PageHeading from '@/components/PageHeading.vue'
import ProjectCard from '@/components/ProjectCard.vue'
import EmptyState from '@/components/EmptyState.vue'
import NoticeBox from '@/components/NoticeBox.vue'
const { projects, loading, error, reload, favorite } = useLibrary(), search = ref(''), filter = ref('all'), sort = ref('updated'), layout = ref('grid')
const results = computed(() => projects.value.filter(p => `${p.name} ${p.location}`.toLowerCase().includes(search.value.trim().toLowerCase()) && (filter.value !== 'favorites' || p.favorite)).sort((a, b) => sort.value === 'name' ? a.name.localeCompare(b.name) : b.updatedAt.localeCompare(a.updatedAt)))
</script>
<template><div class="container"><PageHeading eyebrow="YOUR LOCAL LIBRARY" title="Every space, in one place." subtitle="Your saved projects, ready to explore, edit and export."><RouterLink to="/new" class="btn btn-primary"><AppIcon name="plus"/>New space</RouterLink></PageHeading><div class="library-toolbar card"><div class="search-field"><AppIcon name="search"/><input v-model="search" class="form-control" type="search" placeholder="Search spaces or locations" aria-label="Search spaces"></div><div class="segmented"><button :class="{ active: filter === 'all' }" @click="filter = 'all'">All spaces</button><button :class="{ active: filter === 'favorites' }" @click="filter = 'favorites'">Favorites</button></div><select v-model="sort" class="form-select" aria-label="Sort spaces"><option value="updated">Recently updated</option><option value="name">Name A–Z</option></select><button class="icon-button" :aria-label="layout === 'grid' ? 'Use list layout' : 'Use grid layout'" @click="layout = layout === 'grid' ? 'list' : 'grid'"><AppIcon :name="layout === 'grid' ? 'list' : 'grid'"/></button></div><NoticeBox v-if="error" kind="error">{{ error }}<button class="text-link" @click="reload">Try again</button></NoticeBox><p class="results-count">{{ results.length }} {{ results.length === 1 ? 'space' : 'spaces' }}<span><AppIcon name="lock" :size="14"/>Only on this device</span></p><div v-if="loading" class="skeleton-grid" aria-label="Loading saved spaces"><div v-for="i in 3" :key="i" class="skeleton-card"/></div><div v-else-if="results.length" class="project-grid" :class="{ 'list-layout': layout === 'list' }"><ProjectCard v-for="p in results" :key="p.id" :project="p" @favorite="favorite"/></div><EmptyState v-else :title="projects.length ? 'No matching spaces' : 'Room for something new.'" :message="projects.length ? 'Try a different search or switch to all spaces.' : 'Create your first project to scan a room, import a model, or collect reference photos.'"><RouterLink to="/new" class="btn btn-primary"><AppIcon name="plus"/>Create a space</RouterLink><RouterLink to="/import" class="btn btn-outline-primary">Import a backup</RouterLink></EmptyState></div></template>
