<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import PageHeading from '@/components/PageHeading.vue'
import AppIcon from '@/components/AppIcon.vue'
import NoticeBox from '@/components/NoticeBox.vue'
import { newProject } from '@/domain/types'
import { repository } from '@/data/database'
import { errorMessage } from '@/domain/validation'
const name = ref(''), location = ref(''), method = ref('scan'), busy = ref(false), error = ref(''), router = useRouter()
async function create(): Promise<void> { if (busy.value) return; busy.value = true; error.value = ''; try { const project = newProject(name.value, location.value); await repository.create(project); await router.push(`/projects/${project.id}${method.value === 'scan' ? '/scan' : method.value === 'import' ? '/import' : ''}`) } catch (e) { error.value = errorMessage(e) } finally { busy.value = false } }
</script>
<template><div class="container narrow"><PageHeading back="/" eyebrow="LET’S BRING IT INTO FOCUS" title="A new space." subtitle="Give your project a name. Everything starts here."/><form class="card form-card" @submit.prevent="create"><div class="form-illustration"><AppIcon name="cube" :size="56"/><span>CAPTURE WHAT MATTERS</span></div><label class="form-label" for="space-name">Space name <span class="required">*</span></label><input id="space-name" v-model="name" class="form-control" maxlength="100" required pattern=".*\S.*" placeholder="e.g. My apartment, Living room"><label class="form-label mt-4" for="space-location">Location <span class="optional">optional · private</span></label><input id="space-location" v-model="location" class="form-control" maxlength="200" placeholder="e.g. Kuala Lumpur"><fieldset class="mt-4"><legend class="form-label">How would you like to begin?</legend><label v-for="m in [{ id: 'scan', title: 'Scan with this phone', text: 'Check support, then capture in real time.', icon: 'scan' }, { id: 'import', title: 'Import an existing model', text: 'GLB, PLY or OBJ. No upload required.', icon: 'upload' }, { id: 'organize', title: 'Set up the space first', text: 'Add notes and reference photos.', icon: 'folder' }]" :key="m.id" class="choice-card" :class="{ selected: method === m.id }"><input v-model="method" type="radio" name="method" :value="m.id"><AppIcon :name="m.icon" :size="25"/><span><strong>{{ m.title }}</strong><small>{{ m.text }}</small></span><AppIcon v-if="method === m.id" name="check" :size="20"/></label></fieldset><NoticeBox v-if="error" kind="error">{{ error }}</NoticeBox><button class="btn btn-primary btn-lg w-100 mt-4" type="submit" :disabled="busy || !name.trim()">{{ busy ? 'Creating your space…' : 'Create space & continue' }}<AppIcon name="arrow"/></button><p class="form-footnote"><AppIcon name="shield" :size="15"/>No account needed. Stored on this device.</p></form><RouterLink to="/import" class="below-form-link">Already have a project backup? Restore a W3D file<AppIcon name="arrow" :size="16"/></RouterLink></div></template>
